### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by rawkode** [devtechscot/manifesto#3]
We should provide a Code of Conduct, or pick an existing one, that we wish to suggest / advise / enforce(?) for user groups / members of DevTechScot.

**Comment by rawkode** [comment]
As well as being for "Member Groups" (Pending definition), this should also be "signed" (Whatever we mean by "signed" / "accepted") by anyone joining our Communication Platform (#1)

**Comment by carmemias** [comment]
It may be a good starting point to take a Code of Coduct already used by one of the "member groups" and amend it to reflect the fact the nature of DevTechScot... 

We use this: [WPGlasgow Code of Conduct](https://wpglasgow.org/code-of-conduct/) which was in turn amalgamated from various examples I found online. Most of the sections used for face-to-face events can also be applied to online communication, regardless of the tool used for that.
